name: meu_app_testes
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  http: ^0.13.5
  mockito: ^5.3.0
  # path: ^1.8.0

dev_dependencies:
build_runner: ^2.2.0
  lints: ^3.0.0
  test: ^1.16.0
